export const ActionTypes = {
  SET_PRODUCTS: "SET_PRODUCTS",
  SELECTED_PRODUCT: "SELECTED_PRODUCT",
  INCREASE_PRODUCT: "INCREASE_PRODUCT",
  DECREASE_PRODUCT: "DECREASE_PRODUCT",
  GET_TOTAL: "GET_TOTAL",
  CLEAR_ITEM: "CLEAR_ITEM",
  REMOVE_PRODUCT: "REMOVE_PRODUCT",
};
